"""各 Agent 角色的系统提示词（统一引用默认提示词库）"""

from agents.default_prompts import (
    OUTLINE_WRITER_SYSTEM_PROMPT,
    CHARACTER_DESIGNER_SYSTEM_PROMPT,
    CHAPTER_WRITER_SYSTEM_PROMPT,
    REVIEWER_SYSTEM_PROMPT,
    EDITOR_SYSTEM_PROMPT,
)

OUTLINE_WRITER = OUTLINE_WRITER_SYSTEM_PROMPT
CHARACTER_DESIGNER = CHARACTER_DESIGNER_SYSTEM_PROMPT
CHAPTER_WRITER = CHAPTER_WRITER_SYSTEM_PROMPT
REVIEWER = REVIEWER_SYSTEM_PROMPT
EDITOR = EDITOR_SYSTEM_PROMPT
